<html>
  <head>
    <title>Zahlenraten</title>
  </head>
    <body>
      <h1>Glückwunsch du hast gewonnen</h1>
      <p><h2>Du hast <?php echo "test";//$_SESSION['versuche'];?> gebraucht. </h2></p>
    <form action="index.php" method="post" name="formular1" id="formular1">
        <input type="submit" name="restart" size="25" value="Hier neustarten" maxlength="100" />
      </p>
    </form>
  </body>

</html>
