<html>
  <head>
    <title>Zahlenraten</title>
  </head>
    <body>
      <h1>Du hast gewonnen!</h1>
    <form action="index.php" method="post" name="formular1" id="formular1">
        <input type="submit" name="restart" size="25" value="Neustarten" maxlength="100" />
    </form>
    <form action="endscreen.phtml" method="post" name="formular2" id="formular2">
            <input type="submit" name="save" size="25" value="Speichern" maxlength="100" />
      </p>
    </form>
  </body>

</html>
