<html>

<head>
</head>

<body>



<table border="1">

  <tr>

<th><h1> Spiel </h1></th>

<th><h1> gesuchte Zahl </h1></th>

<th><h1> Versuche </th></h1>


<th><h1> Zeitstempel </th></h1>


<tr>

<td>
    1 <br /> <br />
    2 <br /> <br />
    3 <br /> <br />
    4 <br /> <br />
    5 <br /> <br />
    6 <br /> <br />
    7 <br /> <br />

</td>

<td>
    25 <br /> <br />
    43 <br /> <br />
    65 <br /> <br />
    76 <br /> <br />
    21 <br /> <br />
    56 <br /> <br />
    90 <br /> <br />
</td>

<td>
  11 <br /> <br />
  5 <br />  <br />
  7 <br />  <br />
  4 <br />  <br />
  5 <br />  <br />
  1 <br />  <br />
  0 <br />  <br />
</td>

</table>


<div align="center">





<br /> <br />
<form action="highscore.phtml" method="post" name="formular2" id="formular2">
      <input type="submit" name="save" size="25" value="Zur Highscore Liste" maxlength="100" />




  </body
